{% set name = "update_checker" %}
{% set version = "0.16" %}
{% set sha256 = "70e39446fccf77b21192cf7a8214051fa93a636dc3b5c8b602b589d100a168b8" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  noarch: python
  script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
  build:
    - python
    - setuptools

  run:
    - python
    - requests >=2.3.0

test:
  imports:
    - update_checker

about:
  home: https://github.com/bboe/update_checker
  license: BSD-2-Clause
  license_family: BSD
  license_file: LICENSE.txt
  dev_url: https://github.com/bboe/update_checker
  summary: A python module that will check for package updates.

extra:
  recipe-maintainers:
    - proinsias
    - bollwyvl
