travis:
  secure:
    BINSTAR_TOKEN: ZCn6SkbZVZD+KbQutuLZZZI1RjVZC36rvi7irsWkyhL7PjntJOxn0dKXttEKxCWwAfhPCnRKB6PVvgA6TKDD+Ks4piwJx/m9s3K/ub73EJGzSuhWEFqIh2i67hKUROjHHDuREe4zrxjCO6qbI/v+B2YJBohiskviIKAG2P/0ASZonEV3vNRH8SYLKHqx17YQoz2sBxDX+NTPE8Te1RPLomIBQi+i4194wjJZtbPBeCWxRZAlIc1Fvla/XX+YI+T/tla6jOnhy/0PPMPfnxhpCV/T5JdmxvjsJjCMaNbyGxJ1E1sBIva90QF7aW1IumjzDzIBf+lu716L1gLWxA0m2wDXXxL5kfZxuYkIymkLWh61HC58VF37qGlEYeW4DgolYIg1r/xI12y0Q62VuMYcWXLP9d7VNoKgZ2D5Rpg7tQRharL9FZaSkqzYqWDzp2Y2YMT0waOhOCkhznnMaNPvFOKrUmf0ZxwFxxEDtAItK/bQID0UC8qa8YwX0tMe5C1Mz0Cfa1fRLLc2N2BtsJeSlKaPpwC3Crt0OkHnZ54ColnqVSmTMI/WgBb4oA9B+qBqmSrBqimIPQbo6mcuU7s66mnNEdlNamgCQ7cK1m2EYhN/NKZdRNicdnjf+p7oLbhyyN5Uljvzbmy3mT29HixTOLelYMEIAF1KA+AG0466BDg=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
