travis:
  secure:
    BINSTAR_TOKEN: WtDk7eVCD+4r3+4HSdsL96+IjCM/6SMK7EX1cnGqAMBlj/gN1zRrvRV9A9DpXwA5D6HtBhJDUiTD/PBVTiZGbmx4fG0m2+F/zS4FrzO9PducTVv54FOVJpBeQnrV5IDRS2ROeDZAVVQuWJwf16+qzIvug/sgwqijCsxrEd9bFqD6tBMG4V13WvomXC5xl42vRJzFJaS4+uu8B8rmQw0DcS12zLHtgzG8Vet+Q9T7zhnHqjgRhRVu2mWu6d7otBd+0Xc+Fz5q3c2dVlF3aS4fCexVY1zuAPnw5Sljy0Bt94brsXMTpqbJSbMmyVysRHpWmygLodVsRUI7uSq/7YSGASoxiszqxGQjtY18e9hl5wpvXY4jrmNQErXli64QGTSJCXmhO23uFp1MVecYCUAvrfqoxXRSwekYVsrmFxrMt3BA/4HD2TpoJ7vd+PdkVSoLgaBm+SjUAa2LcR56AOLVlXMqnncuvXWTCRfy92dJl05UzTLGm1RXqIZXV1dYrLRczmu9mvjorbi9uZpRRZGLxCWOe//tpaD2GPRuBHmZo45RWtS7Map5+ek8wSPNtOWKswxjAcNroh8R71GLH9fm0S7S7zyVJ+3nrf8xM/v1NAMz8oBxJNXXR14pB6eY4Yd+zjzU2mtlsKVPk0v8KKFza4RbBYZ5pYkTqnhAgtUySw4=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
